
#define ADNED_MAX_STRING_SIZE 256
#define ADNED_MAX_DETS 4
#define ADNED_MAX_CHANNELS 4

#define ADNED_MAX_TRANSFORM_PARAMS 6
#define ADNED_TRANSFORM_NONE 0
#define ADNED_TRANSFORM_ARRAY 1
#define ADNED_TRANSFORM_DSPACE 2
#define ADNED_TRANSFORM_DELTAE 3


